chore: enable clippy for errors only

diff --git a/.github/actions/style/action.yml b/.github/actions/style/action.yml
--- a/.github/actions/style/action.yml
+++ b/.github/actions/style/action.yml
@@ -30,15 +30,21 @@ runs:
         echo "Checking for Rust code changes..."
         if echo "$ALL_CHANGED_FILES" | grep -q '\.rs$'; then
           echo "Running checks for the Rust code..."
+
+        # Install the nightly toolchain
+          rustup toolchain install nightly
+
+          # Install rustfmt for the nightly toolchain
+          rustup component add rustfmt --toolchain nightly
+
           if ! cargo +nightly fmt -- --check; then
             echo "Rust code is not properly formatted."
             exit 1  # Exit with a non-zero status code if formatting fails
           fi
-          # TODO: Uncomment after fixing clippy issues
-          # if ! cargo clippy -- -D warnings; then
-          #   echo "Rust code is not properly linted."
-          #   exit 1  # Exit with a non-zero status code if formatting fails
-          # fi
+          if ! cargo clippy; then
+            echo "Rust code is not properly linted."
+            exit 1  # Exit with a non-zero status code if formatting fails
+          fi
         fi
 
     # Check for changes in the 'node-ui' directory and run formatting/linting
