fix: Fixed lots of linting (#730)
  - Upgraded toolchain to Rust 1.81.

  - Added additional lints that have recently been stabilised.

  - Added reasons for lint exceptions.

  - Fixed all recently-introduced lint failures.

diff --git a/.github/actions/style/action.yml b/.github/actions/style/action.yml
--- a/.github/actions/style/action.yml
+++ b/.github/actions/style/action.yml
@@ -27,6 +27,10 @@ runs:
             echo "Rust code is not properly formatted."
             exit 1  # Exit with a non-zero status code if formatting fails
           fi
+          if ! cargo clippy -- -D warnings; then
+            echo "Rust code is not properly linted."
+            exit 1  # Exit with a non-zero status code if formatting fails
+          fi
         fi
 
     # Check for changes in the 'node-ui' directory and run formatting/linting
