how about here?

diff --git a/.github/workflows/ci-checks-ignored.yml b/.github/workflows/ci-checks-ignored.yml
--- a/.github/workflows/ci-checks-ignored.yml
+++ b/.github/workflows/ci-checks-ignored.yml
@@ -16,3 +16,21 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - run: echo "Ignored"
+
+  stage:
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+    steps:
+      - id: download
+        run: exit 1
+        continue-on-error: true
+
+      - env:
+          S: "${{ success() }}"
+          # F: ${{ failure() }}
+          # A: ${{ always() }}
+          # O: ${{ steps.download.outcome }}
+          # C: ${{ steps.download.conclusion }}
+          # D: ${{ toJson(steps.download) }}
+        run: env
